"""Native Kasane functions. Prefer the typed wrappers in ``kasane``."""

from typing import Mapping

Version = tuple[int, int, int]
Point = tuple[float, float]


class SdkFailure(Exception):
    code: str
    operation: str
    object_ids: list[str]
    field_path: str | None
    expected_version: Version | None
    actual_version: Version | None
    referrers: list[str]


class NativeEdit:
    def add_png_asset(self, id: str, name: str, path: str) -> None: ...
    def create_rectangle(
        self, id: str, name: str, asset_id: str, minimum: Point, maximum: Point
    ) -> None: ...
    def rename_mesh(self, id: str, name: str) -> None: ...
    def update_positions(
        self, id: str, vertex_ids: list[int], positions: list[Point]
    ) -> None: ...
    def create_parameter(
        self,
        id: str,
        name: str,
        minimum: float,
        maximum: float,
        default_value: float,
        repeat: bool = False,
    ) -> None: ...
    def create_mesh_binding(
        self,
        id: str,
        mesh_id: str,
        axes: list[tuple[str, list[float]]],
        forms: list[tuple[list[float], list[Point]]],
    ) -> None: ...
    def commit(self) -> Version: ...
    def cancel(self) -> None: ...
    def abort(self) -> None: ...


class NativeSession:
    def __init__(
        self,
        document_id: str,
        width: float,
        height: float,
        origin_x: float,
        origin_y: float,
        pixels_per_unit: float,
    ) -> None: ...
    @staticmethod
    def open(path: str) -> NativeSession: ...
    def version(self) -> Version: ...
    def modified(self) -> bool: ...
    def project_path(self) -> str | None: ...
    def mesh_ids(self) -> list[str]: ...
    def asset_ids(self) -> list[str]: ...
    def parameter_ids(self) -> list[str]: ...
    def parameter(self, id: str) -> tuple[str, str, float, float, float, bool] | None: ...
    def mesh(self, id: str) -> tuple[str, str, list[int], list[Point]] | None: ...
    def diagnose_resources(self) -> list[tuple[str, str, str]]: ...
    def evaluate(
        self, values: Mapping[str, float]
    ) -> tuple[list[tuple[str, float, float, bool]], list[tuple[str, list[Point]]]]: ...
    def start_edit(self, label: str, expected_version: Version | None = None) -> NativeEdit: ...
    def save(
        self, path: str, expected_version: Version | None = None
    ) -> tuple[str, bool, list[str], list[str]]: ...
    def import_model3(
        self, path: str, expected_version: Version | None = None
    ) -> tuple[Version, int, list[tuple[str, str, str]], list[str]]: ...
    def import_bare_moc3(
        self,
        path: str,
        texture_map: Mapping[int, str],
        expected_version: Version | None = None,
    ) -> tuple[Version, int, list[tuple[str, str, str]], list[str]]: ...
    def export_package(
        self, destination: str, expected_version: Version | None = None
    ) -> tuple[bool, bool, list[str]]: ...
    def undo(self) -> Version: ...
    def redo(self) -> Version: ...


def capabilities() -> dict[str, bool]: ...
