"""Native Kasane functions. Prefer the typed wrappers in ``kasane``."""

from typing import Mapping

Version = tuple[int, int, int]
Point = tuple[float, float]
Mesh = tuple[str, str, list[int], list[Point], Version]
Parameter = tuple[str, str, float, float, float, bool, Version]
Asset = tuple[str, str, str, int, int, str, Version]
MeshBinding = tuple[str, str, list[tuple[str, list[float]]], list[tuple[list[float], list[Point]]], Version]
DrawOrderGroup = tuple[str, list[str], int, int]
Part = tuple[str, str, str, str, bool, float, Version]
Rotation = tuple[float, tuple[float, float, float, float, bool, bool]]
Warp = tuple[int, int, bool, list[Point]]
Transform = tuple[str, str, str, str | None, str | None, str, Rotation | None, Warp | None, bool, Version]
Evaluation = tuple[list[tuple[str, float, float, bool]], list[tuple[str, list[Point]]]]


class SdkFailure(Exception):
    code: str
    operation: str
    object_ids: list[str]
    field_path: str | None
    expected_version: Version | None
    actual_version: Version | None
    referrers: list[str]


class ObjectHandle:
    @property
    def id(self) -> str: ...
    @property
    def kind(self) -> str: ...


class NativeEdit:
    def add_png_asset_from_base(
        self, id: str, name: str, base: str, relative: str
    ) -> None: ...
    def replace_png_asset(self, id: str, name: str, path: str) -> None: ...
    def relocate_png_asset(self, id: str, path: str) -> None: ...
    def create_rotation_transform(
        self, id: str, name: str, part_id: str | None,
        parent_id: str | None, rotation: Rotation
    ) -> None: ...
    def create_warp_transform(
        self, id: str, name: str, part_id: str | None, parent_id: str | None,
        rows: int, columns: int, quad: bool, points: list[Point]
    ) -> None: ...
    def update_rotation(self, id: str, rotation: Rotation) -> None: ...
    def update_warp_points(self, id: str, points: list[Point]) -> None: ...
    def create_part(
        self, id: str, name: str, parent_id: str = "", enabled: bool = True,
        draw_order: float = 0.0
    ) -> None: ...
    def replace_part(
        self, id: str, name: str, parent_id: str, enabled: bool, draw_order: float
    ) -> None: ...
    def replace_draw_order_groups(self, groups: list[DrawOrderGroup]) -> None: ...
    def replace_canvas(
        self, width: float, height: float, origin_x: float, origin_y: float, pixels_per_unit: float
    ) -> None: ...
    def erase_object(self, id: str) -> None: ...
    def replace_parameter(
        self, id: str, name: str, minimum: float, maximum: float,
        default_value: float, repeat: bool = False
    ) -> None: ...
    def set_organization_parent(self, part_id: str, parent_id: str) -> None: ...
    def set_transform_parent(self, transform_id: str, parent_id: str | None) -> None: ...
    def set_transform_part(self, transform_id: str, part_id: str | None) -> None: ...
    def set_deform_parent(self, mesh_id: str, transform_id: str) -> None: ...
    def set_mesh_part(self, mesh_id: str, part_id: str) -> None: ...
    def add_png_asset(self, id: str, name: str, path: str) -> None: ...
    def create_rectangle(
        self, id: str, name: str, asset_id: str, minimum: Point, maximum: Point
    ) -> None: ...
    def rename_mesh(self, id: str, name: str) -> None: ...
    def update_positions(
        self, id: str, vertex_ids: list[int], positions: list[Point]
    ) -> None: ...
    def create_parameter(
        self,
        id: str,
        name: str,
        minimum: float,
        maximum: float,
        default_value: float,
        repeat: bool = False,
    ) -> None: ...
    def create_mesh_binding(
        self,
        id: str,
        mesh_id: str,
        axes: list[tuple[str, list[float]]],
        forms: list[tuple[list[float], list[Point]]],
    ) -> None: ...
    def commit(self) -> Version: ...
    def cancel(self) -> None: ...
    def abort(self) -> None: ...


class NativeSession:
    def __init__(
        self,
        document_id: str,
        width: float,
        height: float,
        origin_x: float,
        origin_y: float,
        pixels_per_unit: float,
    ) -> None: ...
    @staticmethod
    def with_history_limits(
        document_id: str, width: float, height: float, origin_x: float,
        origin_y: float, pixels_per_unit: float, max_steps: int, max_bytes: int
    ) -> NativeSession: ...
    @staticmethod
    def open(path: str) -> NativeSession: ...
    def version(self) -> Version: ...
    def new_project(
        self,
        document_id: str,
        width: float,
        height: float,
        origin_x: float,
        origin_y: float,
        pixels_per_unit: float,
        expected_version: Version | None = None,
    ) -> Version: ...
    def document_id(self) -> str: ...
    def canvas(self) -> tuple[float, float, float, float, float]: ...
    def draw_order_groups(self) -> list[DrawOrderGroup] | None: ...
    def evaluation_revision(self) -> int: ...
    def modified(self) -> bool: ...
    def project_path(self) -> str | None: ...
    def mesh_ids(self) -> list[str]: ...
    def asset_ids(self) -> list[str]: ...
    def asset(self, id: str) -> Asset | None: ...
    def references_to(self, id: str) -> list[str]: ...
    def parameter_ids(self) -> list[str]: ...
    def binding_ids(self) -> list[str]: ...
    def part_ids(self) -> list[str]: ...
    def transform_ids(self) -> list[str]: ...
    def scene_binding_ids(self) -> list[str]: ...
    def blend_key_table_ids(self) -> list[str]: ...
    def blend_constraint_ids(self) -> list[str]: ...
    def blend_binding_ids(self) -> list[str]: ...
    def glue_ids(self) -> list[str]: ...
    def offscreen_ids(self) -> list[str]: ...
    def parameter(self, id: str) -> Parameter | None: ...
    def mesh(self, id: str) -> Mesh | None: ...
    def binding(self, id: str) -> MeshBinding | None: ...
    def binding_for_mesh(self, mesh_id: str) -> MeshBinding | None: ...
    def part(self, id: str) -> Part | None: ...
    def transform(self, id: str) -> Transform | None: ...
    def handle(self, kind: str, id: str) -> ObjectHandle: ...
    def resolve_handle(self, handle: ObjectHandle) -> None: ...
    def mesh_by_handle(self, handle: ObjectHandle) -> Mesh: ...
    def find_meshes_by_name(self, name: str) -> list[Mesh]: ...
    def require_unique_mesh(self, name: str) -> Mesh: ...
    def geometry(
        self, id: str
    ) -> tuple[Version, str, list[int], list[Point], list[Point], list[tuple[int, int, int]], str, str | None] | None: ...
    def validate_structure(self) -> list[tuple[str, str, str]]: ...
    def history_state(self) -> tuple[int, int, int, int, int]: ...
    def history_lengths(self) -> tuple[int, int]: ...
    def estimated_content_bytes(self) -> int: ...
    def drain_events(self) -> list[tuple[str, Version, Version, str, list[str], bool]]: ...
    def diagnose_resources(self) -> list[tuple[str, str, str]]: ...
    def evaluate(self, values: Mapping[str, float]) -> Evaluation: ...
    def preview_values(self) -> dict[str, float]: ...
    def preview_revision(self) -> int: ...
    def preview_evaluation_count(self) -> int: ...
    def preview_frame(self) -> Evaluation: ...
    def set_preview_values(self, values: Mapping[str, float]) -> bool: ...
    def set_preview_parameter(self, id: str, value: float) -> bool: ...
    def reset_preview_values(self) -> bool: ...
    def start_edit(self, label: str, expected_version: Version | None = None) -> NativeEdit: ...
    def save(
        self, path: str, expected_version: Version | None = None
    ) -> tuple[str, bool, list[str], list[str]]: ...
    def import_model3(
        self, path: str, expected_version: Version | None = None
    ) -> tuple[Version, int, list[tuple[str, str, str]], list[str]]: ...
    def import_bare_moc3(
        self,
        path: str,
        texture_map: Mapping[int, str],
        expected_version: Version | None = None,
    ) -> tuple[Version, int, list[tuple[str, str, str]], list[str]]: ...
    def export_package(
        self, destination: str, expected_version: Version | None = None
    ) -> tuple[bool, bool, list[str]]: ...
    def undo(self) -> Version: ...
    def redo(self) -> Version: ...


def capabilities() -> dict[str, bool]: ...
