[package]
name = "kasane-godot"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
godot = { version = "0.5", features = ["api-4-3", "experimental-threads"] }
kasane-core = { path = "../kasane-core" }
kasane-project = { path = "../kasane-project" }
kasane-moc3 = { path = "../kasane-moc3" }
serde = { workspace = true }
serde_json = { workspace = true }
