[package]
name = "kasane-render-godot"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
godot = { version = "0.5", features = ["api-4-3", "experimental-threads"] }
kasane-core = { path = "../kasane-core" }
kasane-render = { path = "../kasane-render" }
