[package]
name = "kasane-render-metal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bytemuck = { workspace = true }
kasane-core = { path = "../kasane-core" }
kasane-render = { path = "../kasane-render" }
thiserror = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
metal = "0.33"
